# ========= Imports =========
from __future__ import annotations
import matplotlib.pyplot as plt
_MPL_PLT = plt  # unshadowed alias -- see plots_maxent_sprt's per-call `plt` shadow
from pathlib import Path
from typing import Dict, Any, Sequence, Optional

import numpy as np
from scipy.stats import norm as _norm_dist
import matplotlib.patches as _mpatches

from ..utils.types import IndicatorResult, SignalData

from .plot_style import (
    ARTICLE_RCPARAMS, FIGSIZE_SIMPLE, FIGSIZE_WIDE, SCALE,
    COLORS, figsize_grid, figsize_from_scale, apply_sci_yaxis,
)

# Alias hacia la paleta compartida (article-plot-style, Okabe-Ito) -- se
# mantienen estos nombres para no tocar los ~40 call-sites de este archivo.
color_red    = COLORS["threshold"]
color_orange = COLORS["chatter"]
color_purple = COLORS["accent_purple"]
color_verde  = COLORS["accent_green"]
color_azul   = COLORS["stable"]


def fig_size(scale=1.0, ncols=1, nrows=1, base_width=None):
    """Compat shim: article-plot-style preset scaled, grid-generalized.

    ``base_width`` is accepted but ignored (kept only so old call sites with
    a positional/keyword base_width don't break) -- FIGSIZE_SIMPLE's width
    is now the single source of truth for 1 column.
    """
    return figsize_from_scale(figsize_grid(ncols, nrows), scale)


def configurar_estilo_global() -> None:
    """Apply the shared article-style rcParams (see plot_style.py)."""
    plt.rcParams.update(ARTICLE_RCPARAMS)


def plots_maxent_sprt(
    signal: Optional[SignalData],
    result: IndicatorResult,
    show_signal: bool = True,
    show: bool = True,
    zoom_x: Optional[tuple[float, float]] = None,
    zoom_y: Optional[tuple[float, float]] = None,
    vlines: Optional[Sequence[float]] = None,
    hlines: Optional[Sequence[float]] = None,
    t_gt: Optional[float] = None,
    scale: float = SCALE,
    figsize_simple: tuple[float, float] = FIGSIZE_SIMPLE,
    figsize_wide: tuple[float, float] = FIGSIZE_WIDE,
    grid_scale: Optional[float] = None,

) -> plt.Figure:
    """
    Generate the standard diagnostic figure set for a MaxEnt-SPRT run.

    The function consumes the final detection result and the metadata stored in
    ``IndicatorResult.meta`` to produce publication-oriented plots covering the
    raw signal, OPR sampling, fitted Gaussian models, entropy history, and SPRT
    statistic evolution.

    :param signal: Original signal bundle used as the plotting reference. The function currently expects access to its analysis time axis and signal array.
    :param result: Detection output containing the indicator history and the metadata artifacts generated by the pipeline.
    :param show_signal: Reserved flag indicating whether the signal plot should be displayed as part of the figure set.
    :param show: Reserved flag for interactive display control.
    :param zoom_x: Optional x-axis range shared by several panels.
    :param zoom_y: Optional y-axis range shared by several panels.
    :param vlines: Optional vertical reference lines, typically event times or manual annotations.
    :param hlines: Optional horizontal reference lines, typically thresholds or guide values.

    Returns:
        plt.Figure: Final Matplotlib figure object associated with the last plot
        created by the routine.
    """
    # Shadow the module-level preset/shim -- every nested closure below refers
    # to `FIGSIZE_SIMPLE`/`fig_size` as a free variable, so this local redefinition
    # (Python closure scoping) is enough to honor a per-call override without
    # touching each of the ~40 individual `fig_size(...)` call sites.
    FIGSIZE_SIMPLE = figsize_simple
    FIGSIZE_WIDE = figsize_wide
    # Per-case grid figures (F0a/F0b/F1/F2/F6a/F6b) can pack many square cells
    # into one figure -- independent from `scale` so grids can be sized up
    # without also inflating every single-panel figure. Defaults to `scale`
    # (unchanged behavior) unless the caller passes its own value.
    if grid_scale is None:
        grid_scale = scale

    # ── Case identifier -- every figure this call creates is tagged with it,
    # both in its window identity (num=) and its visible title. Without this,
    # every call reuses the SAME fixed num= strings ("F0a — ...", "D7 — ...",
    # etc.), so calling this dispatcher again for a DIFFERENT case/signal in
    # the same process (e.g. a DOE loop comparing many cases) silently
    # overwrites the previous case's windows instead of opening new ones.
    # Window identity only -- visible titles stay generic (curve name only,
    # no case), so a saved/exported figure reads cleanly on its own.
    _case_id = None
    if signal is not None:
        _case_id = (signal.meta or {}).get("signal_id")
        if not _case_id and signal.path:
            _case_id = Path(signal.path).stem
    _case_id = _case_id or "signal"

    _real_plt = _MPL_PLT

    class _PltShadow:
        @staticmethod
        def subplots(*_args, num=None, **_kwargs):
            if num is not None:
                num = f"{num} — {_case_id}"
            return _real_plt.subplots(*_args, num=num, **_kwargs)

        def __getattr__(self, _name):
            return getattr(_real_plt, _name)

    plt = _PltShadow()

    def fig_size(scale=1.0, ncols=1, nrows=1, base_width=None):
        return figsize_from_scale(figsize_grid(ncols, nrows, base=FIGSIZE_SIMPLE), scale)

    def _plot_S_n(
        t_i, I, lim_sup: float, lim_inf: float,
        scale: float = 1.0,
        title: str = "Tool Velocity - OPR Sampled",
        zoom_x: Optional[tuple[float, float]] = None,
        zoom_y: Optional[tuple[float, float]] = None,
        vlines: Optional[Sequence[float]] = None,
        hlines: Optional[Sequence[float]] = None,
        size: Optional[tuple[float, float]] = None,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        if size is None and scale is not None:
            fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        else:
            fig, ax = plt.subplots(figsize=size, constrained_layout=True, num=fig_label)

        ax.plot(t_i, I, label=r"$S_k$", marker='o', color=color_purple, markersize=1)
        ax.axhline(y=lim_sup, color=color_red,  linestyle='--', label=r"$b$ (chatter, $\alpha$)")
        ax.axhline(y=lim_inf, color=color_azul, linestyle='--', label=r"$a$ (stable, $\beta$)")
        ax.axhline(y=0,       color='gray',      linestyle=':')
        ax.text(0.99, lim_sup, f"$b = {lim_sup:.4g}$",
                transform=ax.get_yaxis_transform(),
                color=color_red, ha='right', va='bottom', fontsize=16, clip_on=True)
        ax.text(0.99, lim_inf, f"$a = {lim_inf:.4g}$",
                transform=ax.get_yaxis_transform(),
                color=color_azul, ha='right', va='bottom', fontsize=16, clip_on=True)

        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)

        _draw_vlines(ax, vlines)

        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)

        # ── Scientific notation on y-axis ─────────────────────────────
        apply_sci_yaxis(ax)

        ax.set_title(title)
        ax.set_xlabel("time (s)")
        ax.set_ylabel(r"$I_{SPRT}$")
        ax.legend()

        return fig, ax

    # ──────────────────────────────────────────────────────────────────
    # NEW SUB-FUNCTIONS
    # ──────────────────────────────────────────────────────────────────

    def _plot_H_time_segment(
        t: np.ndarray,
        H: np.ndarray,
        color,
        title: str = "Entropy",
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """Single entropy sequence vs time (for one region)."""
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        if t is not None and H is not None and len(t) > 0:
            ax.plot(t, H, marker='o', color=color)
        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        _draw_vlines(ax, vlines)
        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Entropy $H$")
        return fig, ax

    def _plot_H_time_one_segment(
        t: np.ndarray,
        H: np.ndarray,
        seg_ranges: list,
        seg_label: str,
        color_all,
        color_seg,
        title: str = "Training Entropy — Interval",
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """H(t) for stable training: full trace faded, one label group highlighted.

        - All H_free vs t_mid_free: light (alpha=0.25, no markers).
        - Label group (union of seg_ranges): full opacity + markers.
        """
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)

        # ── Full trace — faded background ─────────────────────────────────
        if t is not None and H is not None and len(t) > 0:
            ax.plot(t, H, color=color_all, alpha=0.5, lw=1.0,
                    label=rf"All stable")

        # ── Highlighted label group — each range plotted separately ──────
        # (avoids connecting the end of one range to the start of the next)
        if t is not None and H is not None and len(t) == len(H):
            _ranges_str = ", ".join(
                rf"$[{_t0:.2f},\,{_t1:.2f}]$" for _t0, _t1 in seg_ranges
            )
            _n_total_seg = 0
            for _ri, (_t0, _t1) in enumerate(seg_ranges):
                _m = (t >= _t0) & (t <= _t1)
                if not _m.any():
                    continue
                _n_total_seg += int(_m.sum())
                # only the first range carries the legend entry
                _lbl_entry = (
                    rf"{seg_label}  {_ranges_str} s"
                    if _ri == 0 else "_nolegend_"
                )
                ax.plot(
                    t[_m], H[_m],
                    color=color_seg, alpha=1.0, lw=1.6,
                    marker='o', markersize=2,
                    label=_lbl_entry,
                )
            # update legend entry with final n once all ranges are known
            # (already set on first range; re-set to avoid wrong n if multiple ranges)
            if len(seg_ranges) > 1:
                _all_mask = np.zeros(len(t), dtype=bool)
                for _t0, _t1 in seg_ranges:
                    _all_mask |= (t >= _t0) & (t <= _t1)
                _handles, _labels = ax.get_legend_handles_labels()
                for _hi, _lb in enumerate(_labels):
                    if _lb.startswith(seg_label):
                        _labels[_hi] = rf"{seg_label}  {_ranges_str} s"
                        break
                ax.legend(_handles, _labels)

        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        _draw_vlines(ax, vlines)
        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Entropy $H$")
        ax.legend()
        return fig, ax

    def _plot_H_time_all(
        t: np.ndarray,
        H,
        t_split: Optional[float],
        training_intervals=None,
        title: str = "Online Entropy — Full",
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """Full online entropy coloured by training_intervals (if given) or stable (blue) before t_split / chatter (orange) after."""
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        H_arr = np.asarray(H) if H is not None else np.array([])
        if t is not None and H_arr.size > 0:
            if training_intervals is not None and len(training_intervals) > 0:
                from matplotlib.lines import Line2D as _Line2D
                for _t0, _t1, _lbl in training_intervals:
                    _m = (t >= _t0) & (t < _t1)
                    _c = color_azul if str(_lbl).lower() == "stable" else color_orange
                    if np.any(_m):
                        ax.plot(t[_m], H_arr[_m], marker='o', color=_c)
                ax.legend(handles=[
                    _Line2D([0], [0], color=color_azul,   marker='o', label="Stable"),
                    _Line2D([0], [0], color=color_orange, marker='o', label="Chatter"),
                ])
                if t_split is not None:
                    ax.axvline(x=t_split, color="black", linestyle=":", lw=1.2,
                               label=f"$t_{{gt}}$ = {t_split:.3f} s")
                    ax.text(t_split, 0.97, f"  $t_{{gt}}={t_split:.3f}$ s",
                            rotation=90, va="top", ha="right", fontsize=8,
                            color="black", transform=ax.get_xaxis_transform(), clip_on=True)
            elif t_split is not None:
                mask_s = t < t_split
                mask_c = t >= t_split
                if np.any(mask_s):
                    ax.plot(t[mask_s], H_arr[mask_s], marker='o',
                            color=color_azul, label="Stable")
                if np.any(mask_c):
                    ax.plot(t[mask_c], H_arr[mask_c], marker='o',
                            color=color_orange, label="Chatter")
                # ax.axvline(x=t_split, color="black", linestyle=":", lw=1.2,
                #            label=f"$t_{{gt}}$ = {t_split:.3f} s")
                # ax.text(t_split, 0.97, f"  $t_{{gt}}={t_split:.3f}$ s",
                #         rotation=90, va="top", ha="right", fontsize=8,
                #         color="black", transform=ax.get_xaxis_transform())
            else:
                ax.plot(t, H_arr, marker='o', color=color_azul)
        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)

        _draw_vlines(ax, vlines)

        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Entropy $H$")
        ax.legend()
        return fig, ax

    def _plot_PDF_hist(
        H_data: np.ndarray,
        mu: float,
        sigma: float,
        color_hist,
        color_pdf,
        title: str = "PDF Entropy",
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """Histogram of H_data with fitted Gaussian PDF and ±1σ/±2σ/±3σ lines."""
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        if H_data is not None and len(H_data) > 0:
            ax.hist(H_data, density=True, alpha=0.5, color=color_hist, bins=50,
                     label="Histogram")
        # Gaussian curve
        x_pdf = np.linspace(mu - 4.5 * sigma, mu + 4.5 * sigma, 1000)
        y_pdf = np.exp(-0.5 * ((x_pdf - mu) / sigma) ** 2) / (sigma * np.sqrt(2 * np.pi))
        ax.plot(x_pdf, y_pdf, color=color_pdf,
                label=rf"PDF  $\mu$={mu:.4f}, $\sigma$={sigma:.4f}")
        # Vertical reference lines
        ax.axvline(mu, color=color_red, linestyle='-', label=rf"$\mu$ = {mu:.4f}")
        sigma_styles = [('--', 0.85), (':', 0.65), ('-.', 0.45)]
        for k, (ls, alpha) in enumerate(sigma_styles, start=1):
            ax.axvline(mu + k * sigma, color='gray', linestyle=ls, alpha=alpha,
                       label=rf"$\mu\pm{k}\sigma$" if k == 1 else f"$\\pm{k}\\sigma$")
            ax.axvline(mu - k * sigma, color='gray', linestyle=ls, alpha=alpha)
        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        _draw_vlines(ax, vlines)
        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)
        ax.set_title(title)
        ax.set_xlabel("Entropy $H$")
        ax.set_ylabel("Probability Density")
        ax.legend()
        return fig, ax

    def _plot_PDF_hist_one_segment(
        H_data: np.ndarray,
        t_mid: np.ndarray,
        seg_ranges: list,
        mu: float,
        sigma: float,
        seg_label: str,
        color_all,
        color_seg,
        color_pdf,
        title: str = "PDF Entropy — Interval",
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """One figure for one training-label group.

        *seg_ranges* is a list of (t0, t1) pairs belonging to the same label.

        Strategy: compute ONE shared histogram (same bin edges, same
        normalisation denominator = n_total).  The full-data bars are drawn
        first (light), then the segment bars are overlaid using the **same**
        bin edges and the **same** n_total denominator so both layers share
        the exact same Y scale — the segment bars are never taller than the
        full bars.
        - Combined Gaussian PDF (P0 or P1) + mu/sigma lines always on top.
        """
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)

        if H_data is not None and len(H_data) > 0:
            n_bins = 50
            counts_all, bin_edges = np.histogram(H_data, bins=n_bins)
            n_total   = len(H_data)
            widths    = np.diff(bin_edges)
            # shared density normalisation: integral of full histogram = 1
            heights_all = counts_all / (n_total * widths)

            # ── Full combined histogram (light) ───────────────────────
            ax.bar(
                bin_edges[:-1], heights_all, width=widths,
                color=color_all, alpha=0.35, align="edge",
                label=rf"All ",
            )

            # ── Highlighted segment (same normalisation) ──────────────
            if t_mid is not None and len(t_mid) == n_total:
                mask = np.zeros(n_total, dtype=bool)
                for _t0, _t1 in seg_ranges:
                    mask |= (t_mid >= _t0) & (t_mid <= _t1)
                H_seg = H_data[mask]
                if len(H_seg) >= 2:
                    counts_seg, _ = np.histogram(H_seg, bins=bin_edges)
                    heights_seg   = counts_seg / (n_total * widths)
                    _ranges_str   = ", ".join(
                        rf"$[{_t0:.2f},\,{_t1:.2f}]$" for _t0, _t1 in seg_ranges
                    )
                    ax.bar(
                        bin_edges[:-1], heights_seg, width=widths,
                        color=color_seg, alpha=0.72, align="edge",
                        label=rf"{seg_label}  {_ranges_str} s",
                    )

        # ── Fitted Gaussian PDF (whole state) ─────────────────────────
        x_pdf = np.linspace(mu - 4.5 * sigma, mu + 4.5 * sigma, 1000)
        y_pdf = np.exp(-0.5 * ((x_pdf - mu) / sigma) ** 2) / (sigma * np.sqrt(2 * np.pi))
        ax.plot(x_pdf, y_pdf, color=color_pdf, lw=1.8,
                label=rf"PDF  $\mu$={mu:.4f}, $\sigma$={sigma:.4f}")

        # ── mu and sigma reference lines ───────────────────────────────
        ax.axvline(mu, color=color_red, linestyle='-', label=rf"$\mu$ = {mu:.4f}")
        sigma_styles = [('--', 0.85), (':', 0.65), ('-.', 0.45)]
        for k, (ls, alph) in enumerate(sigma_styles, start=1):
            ax.axvline(mu + k * sigma, color='gray', linestyle=ls, alpha=alph,
                       label=rf"$\mu\pm{k}\sigma$" if k == 1 else f"$\\pm{k}\\sigma$")
            ax.axvline(mu - k * sigma, color='gray', linestyle=ls, alpha=alph)

        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        _draw_vlines(ax, vlines)
        if hlines is not None:
            for hy in hlines:
                ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)
        ax.set_title(title)
        ax.set_xlabel("Entropy $H$")
        ax.set_ylabel("Probability Density")
        ax.legend()
        return fig, ax

    def _plot_pieces_grid(
        t, v, piece_sizes,
        t_opr, v_opr, opr_piece_sizes,
        color: str, label: str, title: str,
        zoom_x=None, zoom_y=None,
        vlines=None, hlines=None,
        scale: float = 1.0,
        fig_label: Optional[str] = None,
        ylabel: str = r"Velocity $v(t)$ [m/s]",
    ) -> tuple[plt.Figure, np.ndarray]:
        """Grid of square subplots, one per training piece (stable OR chatter --
        call once per side, never mixed). Each piece is a physically-disjoint
        case (e.g. a separate DOE reference_signal entry): plotting them apart
        instead of one concatenated strip (the old NaN-gap view) makes every
        case individually legible. Falls back to a single full-size panel when
        there's <=1 piece -- nothing to break apart (internal/legacy-cut path).
        """
        t = np.asarray(t, dtype=float) if t is not None else np.array([])
        v = np.asarray(v, dtype=float) if v is not None else np.array([])
        sizes = [int(s) for s in (piece_sizes or []) if s > 0]
        multi = len(sizes) > 1 and sum(sizes) == len(t)

        opr_sizes = [int(s) for s in (opr_piece_sizes or []) if s > 0]
        t_opr_arr = np.asarray(t_opr, dtype=float) if t_opr is not None else np.array([])
        v_opr_arr = np.asarray(v_opr, dtype=float) if v_opr is not None else np.array([])

        def _fill(ax, t_i, v_i, t_o, v_o):
            if t_i.size > 0:
                ax.plot(t_i, v_i, color=color, alpha=0.9, label=label)
            if t_o is not None and t_o.size > 0:
                ax.scatter(t_o, v_o, color=color_red, s=7, zorder=5, label=f"{label} OPR")
            if zoom_x is not None:
                ax.set_xlim(zoom_x)
            if zoom_y is not None:
                ax.set_ylim(zoom_y)
            _draw_vlines(ax, vlines)
            if hlines is not None:
                for hy in hlines:
                    ax.axhline(y=hy, color='gray', linestyle='--', alpha=0.7)

        if not multi:
            fig, ax = plt.subplots(figsize=figsize_from_scale(FIGSIZE_SIMPLE, scale),
                                    constrained_layout=True, num=fig_label)
            _fill(ax, t, v, t_opr_arr if t_opr_arr.size else None, v_opr_arr)
            ax.set_title(title)
            ax.set_xlabel("Time (s)")
            ax.set_ylabel(ylabel)
            ax.legend()
            return fig, np.array([[ax]])

        n = len(sizes)
        ncols = int(np.ceil(np.sqrt(n)))
        nrows = int(np.ceil(n / ncols))
        cell = FIGSIZE_SIMPLE[1]  # square cell, side = SIMPLE preset's height
        # Exception to the usual figsize_grid(base=FIGSIZE_SIMPLE) grid: cells
        # are square (each piece gets ax.set_box_aspect(1) below), not
        # FIGSIZE_SIMPLE's 3.5:2.6 aspect -- still routed through the shared
        # figsize_grid/figsize_from_scale helpers so scaling stays consistent.
        fig, axes = plt.subplots(
            nrows, ncols,
            figsize=figsize_from_scale(figsize_grid(ncols, nrows, base=(cell, cell)), scale),
            constrained_layout=True, num=fig_label, squeeze=False,
        )
        bounds  = np.cumsum(sizes)
        starts  = np.concatenate(([0], bounds[:-1]))
        opr_has_pieces = len(opr_sizes) == n and sum(opr_sizes) == t_opr_arr.size
        if opr_has_pieces:
            opr_bounds = np.cumsum(opr_sizes)
            opr_starts = np.concatenate(([0], opr_bounds[:-1]))

        for i in range(n):
            ax = axes[i // ncols, i % ncols]
            s0, s1 = starts[i], bounds[i]
            t_o = v_o = None
            if opr_has_pieces:
                os0, os1 = opr_starts[i], opr_bounds[i]
                t_o, v_o = t_opr_arr[os0:os1], v_opr_arr[os0:os1]
            _fill(ax, t[s0:s1], v[s0:s1], t_o, v_o)
            ax.set_title(f"Piece {i + 1}", fontsize=10)
            ax.set_box_aspect(1)

        for j in range(n, nrows * ncols):
            fig.delaxes(axes[j // ncols, j % ncols])

        axes[0, 0].legend(fontsize=8)
        fig.suptitle(title, y=1.02)
        fig.supxlabel("Time (s)")
        fig.supylabel(ylabel)
        return fig, axes

    # ──────────────────────────────────────────────────────────────────
    # THEORY / DIAGNOSTIC HELPERS  (D3, D6, D7, D8, D9, H+Sk joint)
    # ──────────────────────────────────────────────────────────────────

    def _nan_split(t, x, piece_sizes):
        """Insert a NaN gap between consecutive pieces in a flat concatenated
        (t, x) view, so a line plot breaks at the seam instead of connecting
        the end of one physically-disjoint piece (e.g. one DOE case) to the
        start of the next. Matplotlib skips NaN samples on its own -- no other
        plotting logic needs to change. A no-op when there's 0-1 pieces (single
        continuous signal, e.g. the internal/legacy-cut path), which keeps
        that case pixel-identical to before this helper existed.
        """
        if t is None or x is None or not piece_sizes or len(piece_sizes) <= 1:
            return t, x
        t = np.asarray(t, dtype=float)
        x = np.asarray(x, dtype=float)
        idx = np.cumsum(piece_sizes)[:-1]
        if idx.size == 0 or idx[-1] > len(t):
            return t, x
        t_parts = np.split(t, idx)
        x_parts = np.split(x, idx)
        t_out = [t_parts[0]]
        x_out = [x_parts[0]]
        for tp, xp in zip(t_parts[1:], x_parts[1:]):
            t_out.append([np.nan]); x_out.append([np.nan])
            t_out.append(tp); x_out.append(xp)
        return np.concatenate(t_out), np.concatenate(x_out)

    def _shade_intervals_local(ax, training_intervals, alpha_bg=0.06):
        """Tint axis background by training-interval label (stable=blue, chatter=orange)."""
        if training_intervals is None:
            return
        for t_lo, t_hi, lbl in training_intervals:
            c = color_azul if str(lbl).lower() == "stable" else color_orange
            ax.axvspan(t_lo, t_hi, alpha=alpha_bg, color=c, zorder=0)

    def _draw_vlines(ax, vlines, default_color="black", default_ls="--"):
        """Draw vertical lines with optional rotated text labels.

        Each entry in *vlines* may be:
        - a plain ``float``            → dashed line, no label
        - ``(float, label)``           → dashed line + vertical label (default_color)
        - ``(float, label, color)``    → dashed line + vertical label (custom color)
        """
        if vlines is None:
            return
        for entry in vlines:
            if isinstance(entry, (list, tuple)):
                vx    = float(entry[0])
                label = str(entry[1]) if len(entry) > 1 else None
                color = entry[2]       if len(entry) > 2 else default_color
            else:
                vx, label, color = float(entry), None, default_color
            ax.axvline(x=vx, color=color, linestyle=default_ls, lw=1.2)
            if label:
                ax.text(
                    vx, 0.97, f"  {label}",
                    rotation=90, va="top", ha="right", fontsize=16,
                    color=color, transform=ax.get_xaxis_transform(),
                clip_on=True)

    def _plot_D3_figure(
        P0_mu, P0_sig, P1_mu, P1_sig,
        alpha_val, beta_val, a_val, b_val,
        scale=5.0,
        fig_label=None,
    ):
        """D3 — P0/P1 separate panels with alpha and beta error fills + SPRT boundary labels."""
        n_sigma = _norm_dist.isf(alpha_val)
        H_thr   = P0_mu + n_sigma * P0_sig
        beta_cl = float(_norm_dist.cdf(H_thr, P1_mu, P1_sig))
        _FS_LBL = 14; _FS_TICK = 12; _FS_LEG = 11; _FS_AX = 13; _LW_PDF = 2.5
        _xlim_L = (P0_mu - 4.2*P0_sig, H_thr + 1.5*P0_sig)
        _xlim_R = (min(P1_mu - 4.2*P1_sig, H_thr - 0.5*P1_sig), P1_mu + 4.2*P1_sig)

        def _grid(lo, hi, mu, sig):
            pts = [mu - 3*sig, mu - sig, mu, mu + sig, mu + 3*sig, H_thr]
            return np.sort(np.unique(np.concatenate([np.linspace(lo, hi, 700), pts])))

        H_gL = _grid(*_xlim_L, P0_mu, P0_sig)
        H_gR = _grid(*_xlim_R, P1_mu, P1_sig)
        pdfL = _norm_dist.pdf(H_gL, P0_mu, P0_sig)
        pdfR = _norm_dist.pdf(H_gR, P1_mu, P1_sig)
        y_pk = max(pdfL.max(), pdfR.max())

        fig, (axL, axR) = plt.subplots(
            1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale), sharey=True,
            constrained_layout=True, num=fig_label)
        fig.suptitle(
            r"SPRT error regions ($\alpha$, $\beta$) and decision boundaries ($a$, $b$)",
            fontsize=_FS_AX + 1)

        for ax, H_g, pdf, mu, sig, C_body, C_tail, xlim, greek, mu_lbl, sub in [
            (axL, H_gL, pdfL, P0_mu, P0_sig, color_azul,   color_red,   _xlim_L, "alpha", r"$\mu_0$", "0"),
            (axR, H_gR, pdfR, P1_mu, P1_sig, color_orange, color_verde, _xlim_R, "beta",  r"$\mu_1$", "1"),
        ]:
            if greek == "alpha":
                ax.fill_between(H_g, pdf, where=(H_g <= H_thr), alpha=0.22, color=C_body)
                ax.fill_between(H_g, pdf, where=(H_g >= H_thr), alpha=0.70, color=C_tail)
                _xt = (H_thr + P0_mu + 3.5*P0_sig) / 2
                ax.text(_xt, _norm_dist.pdf(_xt, mu, sig) + 0.06*y_pk,
                        rf"$\alpha = {alpha_val:.5f}$" + "\n(false alarm)",
                        ha="center", va="bottom", fontsize=_FS_LBL, color=C_tail, fontweight="bold", clip_on=True)
                ax.text(mu, _norm_dist.pdf(mu, mu, sig) + 0.06*y_pk, r"$1-\alpha$",
                        ha="center", va="bottom", fontsize=_FS_LBL + 2, color=C_body, fontweight="bold", clip_on=True)
                leg_h = [
                    _mpatches.Patch(color=C_body, alpha=0.55,
                        label=rf"$P_0$ (stable) $\mathcal{{N}}(\mu_0={P0_mu:.3f},\,\sigma_0={P0_sig:.3f})$"),
                    _mpatches.Patch(color=C_tail, alpha=0.80,
                        label=rf"$\alpha={alpha_val:.5f}$ - false alarm (right tail $P_0$)"),
                    _mpatches.Patch(color=C_body, alpha=0.22,
                        label=rf"$1-\alpha={1-alpha_val:.5f}$ - correct decision"),
                    plt.Line2D([0],[0], color="black", ls="--", lw=2.0,
                        label=rf"$H_{{thr}}=\mu_0+{n_sigma:.1f}\sigma_0={H_thr:.3f}$ nat"),
                    plt.Line2D([0],[0], color=C_body, ls=":", lw=1.5,
                        label=rf"$\mu_0\pm{n_sigma:.1f}\sigma_0$"),
                    plt.Line2D([0],[0], color="none",
                        label=rf"$b=\ln\frac{{1-\beta}}{{\alpha}}={b_val:.2f}$"),
                ]
            else:
                ax.fill_between(H_g, pdf, where=(H_g >= H_thr), alpha=0.22, color=C_body)
                ax.fill_between(H_g, pdf, where=(H_g <= H_thr), alpha=0.70, color=C_tail)
                _xt = (H_thr + P1_mu - 3.5*P1_sig) / 2
                ax.text(_xt, _norm_dist.pdf(_xt, mu, sig) + 0.06*y_pk,
                        rf"$\beta = {beta_cl:.5f}$" + "\n(miss / non-detection)",
                        ha="center", va="bottom", fontsize=_FS_LBL, color=C_tail, fontweight="bold", clip_on=True)
                ax.text(mu, _norm_dist.pdf(mu, mu, sig) + 0.06*y_pk, r"$1-\beta$",
                        ha="center", va="bottom", fontsize=_FS_LBL + 2, color=C_body, fontweight="bold", clip_on=True)
                leg_h = [
                    _mpatches.Patch(color=C_body, alpha=0.55,
                        label=rf"$P_1$ (chatter) $\mathcal{{N}}(\mu_1={P1_mu:.3f},\,\sigma_1={P1_sig:.3f})$"),
                    _mpatches.Patch(color=C_tail, alpha=0.80,
                        label=rf"$\beta={beta_cl:.5f}$ - miss (left tail $P_1$)"),
                    _mpatches.Patch(color=C_body, alpha=0.22,
                        label=rf"$1-\beta={1-beta_cl:.5f}$ - correct detection"),
                    plt.Line2D([0],[0], color="black", ls="--", lw=2.0,
                        label=rf"$H_{{thr}}=\mu_0+{n_sigma:.1f}\sigma_0={H_thr:.3f}$ nat"),
                    plt.Line2D([0],[0], color=C_body, ls=":", lw=1.5,
                        label=rf"$\mu_1\pm{n_sigma:.1f}\sigma_1$"),
                    plt.Line2D([0],[0], color="none",
                        label=rf"$a=\ln\frac{{\beta}}{{1-\alpha}}={a_val:.2f}$"),
                ]
            ax.plot(H_g, pdf, color=C_body, lw=_LW_PDF)
            ax.axvline(H_thr,      color="black", ls="--", lw=2.0)
            ax.axvline(mu,         color=C_body,  ls="-",  lw=1.2, alpha=0.60)
            ax.axvline(mu - 3*sig, color=C_body,  ls=":",  lw=1.5, alpha=0.80)
            ax.axvline(mu + 3*sig, color=C_body,  ls=":",  lw=1.5, alpha=0.80)
            _ya = -0.025 * y_pk
            ax.text(mu,         _ya, mu_lbl,
                    ha="center", va="top", fontsize=_FS_LBL, color=C_body,
                    fontweight="bold", clip_on=False)
            ax.text(mu - 3*sig, _ya, rf"$\mu_{sub}-3\sigma_{sub}$",
                    ha="center", va="top", fontsize=_FS_LBL - 1, color=C_body, clip_on=False)
            ax.text(mu + 3*sig, _ya, rf"$\mu_{sub}+3\sigma_{sub}$",
                    ha="center", va="top", fontsize=_FS_LBL - 1, color=C_body, clip_on=False)
            ax.text(H_thr + 0.2, _ya + 0.25, rf"$H_{{thr}}$",
                    ha="center", va="top", fontsize=_FS_LBL - 1, color="black", clip_on=False)
            ax.set_xlabel(r"Entropy $H$ (nat)", fontsize=_FS_AX)
            ax.set_xlim(*xlim)
            ax.set_ylim(bottom=-0.10 * y_pk, top=y_pk * 1.28)
            ax.legend(handles=leg_h, fontsize=_FS_LEG, loc="upper left",
                      framealpha=0.93, edgecolor="gray")
            ax.tick_params(labelsize=_FS_TICK)
        axL.set_ylabel("Probability density")
        return fig, (axL, axR)

    def _plot_D6_figure(
        P0_mu, P0_sig, P1_mu, P1_sig,
        alpha_val, a_val, b_val,
        scale=5.0,
        fig_label=None,
    ):
        """D6 — ln p0(H), ln p1(H) (left) and Lambda(H) (right) as static functions of H."""
        n_sigma = _norm_dist.isf(alpha_val)
        H_lo = min(P0_mu - 4.5*P0_sig, P1_mu - 4.5*P1_sig)
        H_hi = max(P0_mu + 4.5*P0_sig, P1_mu + 4.5*P1_sig)
        H_r  = np.linspace(H_lo, H_hi, 600)
        ln_p0 = -0.5*((H_r - P0_mu)/P0_sig)**2 - np.log(P0_sig*np.sqrt(2*np.pi))
        ln_p1 = -0.5*((H_r - P1_mu)/P1_sig)**2 - np.log(P1_sig*np.sqrt(2*np.pi))
        Lam_H = ln_p1 - ln_p0
        H_thr   = P0_mu + n_sigma * P0_sig
        H_cross = H_r[np.argmin(np.abs(Lam_H))]

        fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale),
                                          constrained_layout=True, num=fig_label)
        fig.suptitle(
            r"D6 - Log-likelihoods $\ln p_0(H)$,  $\ln p_1(H)$  and  $\Lambda(H) = \ln\,p_1/p_0$",
            fontsize=13)

        ax_a.plot(H_r, ln_p0, color=color_azul,   lw=2.2, label=r"$\ln p_0(H)$  (stable)")
        ax_a.plot(H_r, ln_p1, color=color_orange,  lw=2.2, label=r"$\ln p_1(H)$  (chatter)")
        ax_a.fill_between(H_r, ln_p0, ln_p1, where=(ln_p1 > ln_p0), alpha=0.10, color=color_orange)
        ax_a.fill_between(H_r, ln_p0, ln_p1, where=(ln_p1 < ln_p0), alpha=0.10, color=color_azul)
        for _xv, _lbl, _col, _ls in [
            (P0_mu,   rf"$\mu_0$",          color_azul,   ":"),
            (P1_mu,   rf"$\mu_1$",          color_orange,  ":"),
            (H_thr,   rf"$H_{{thr}}$",      "black",       "--"),
            (H_cross, rf"$\Lambda\!=\!0$",  "gray",        ":"),
        ]:
            ax_a.axvline(_xv, color=_col, ls=_ls, lw=1.0, alpha=0.75)
        for _xv, _lbl, _col, _ha in [
            (P0_mu,   rf"$\mu_0$",          color_azul,   "right"),
            (P1_mu,   rf"$\mu_1$",          color_orange,  "left"),
            (H_thr,   rf"$H_{{thr}}$",      "black",       "right"),
            (H_cross, rf"$\Lambda\!=\!0$",  "gray",        "left"),
        ]:
            ax_a.text(_xv, 0.97, _lbl, color=_col, fontsize=8,
                      ha=_ha, va="top", transform=ax_a.get_xaxis_transform(), clip_on=True)
        ax_a.set_xlabel(r"$H$  (entropy of segment)")
        ax_a.set_ylabel(r"$\ln p(H)$")
        ax_a.set_title(r"Log-likelihoods: parabolas centred on $\mu_0$, $\mu_1$")
        ax_a.legend(fontsize=9, loc="lower center")

        ax_b.plot(H_r, Lam_H, color=color_verde, lw=2.2,
                  label=r"$\Lambda(H) = \ln\frac{p_1(H)}{p_0(H)}$")
        ax_b.fill_between(H_r, Lam_H, 0, where=(Lam_H > 0), alpha=0.10, color=color_orange,
                          label=r"$\Lambda>0 \rightarrow$    votes chatter")
        ax_b.fill_between(H_r, Lam_H, 0, where=(Lam_H < 0), alpha=0.10, color=color_azul,
                          label=r"$\Lambda<0 \rightarrow$    votes stable")
        for _yh, _lbl, _col, _ls in [
            (0,     r"$\Lambda=0$",       "gray",      ":"),
            (b_val, rf"$b={b_val:.2f}$",  color_red,   "--"),
            (a_val, rf"$a={a_val:.2f}$",  color_azul,  "--"),
        ]:
            ax_b.axhline(_yh, color=_col, ls=_ls, lw=1.2, alpha=0.8)
            ax_b.text(0.99, _yh, f"  {_lbl}", color=_col, fontsize=8,
                      ha="right", va="bottom", transform=ax_b.get_yaxis_transform(), clip_on=True)
        ax_b.axvline(H_thr,  color="black", ls="--", lw=1.0, alpha=0.75)
        ax_b.text(H_thr, 0.97, rf"$H_{{thr}}$", color="black", fontsize=8,
                  ha="right", va="top", transform=ax_b.get_xaxis_transform(), clip_on=True)
        ax_b.axvline(H_cross, color="gray", ls=":", lw=0.9, alpha=0.6)
        ax_b.set_xlabel(r"$H$  (entropy of segment)", fontsize=12)
        ax_b.set_ylabel(r"$\Lambda(H) = \ln p_1(H) - \ln p_0(H)$", fontsize=12)
        ax_b.set_title(r"Single-segment log-likelihood ratio $\Lambda(H)$", fontsize=11)
        ax_b.legend(fontsize=9, loc="upper left")

        return fig, (ax_a, ax_b)

    def _plot_D7_figure(
        t_arr, H_arr,
        P0_mu, P0_sig, P1_mu, P1_sig,
        t_gt=None, training_intervals=None,
        scale=5.0,
        fig_label=None,
    ):
        """D7 — p0(H(t)) and p1(H(t)) over time (top) + likelihood ratio p1/p0 (bottom)."""
        _p0_t  = _norm_dist.pdf(H_arr, P0_mu, P0_sig)
        _p1_t  = _norm_dist.pdf(H_arr, P1_mu, P1_sig)
        _ratio = np.where(_p0_t > 1e-300, _p1_t / _p0_t, np.nan)

        fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale),
                                          constrained_layout=True, num=fig_label)
        fig.suptitle(r"D7 - $p_0(H(t))$ and $p_1(H(t))$ over time"
                     "\n(which distribution is more likely at each segment?)", fontsize=12)

        ax_a.plot(t_arr, _p0_t, color=color_azul,   lw=1.2,
                  label=r"$p_0(H(t))$ - how stable-like is this segment?")
        ax_a.plot(t_arr, _p1_t, color=color_orange,  lw=1.2,
                  label=r"$p_1(H(t))$ - how chatter-like is this segment?")
        ax_a.fill_between(t_arr, _p0_t, _p1_t, where=(_p1_t > _p0_t), alpha=0.15,
                          color=color_orange, label=r"$p_1 > p_0 \rightarrow$    chatter wins")
        ax_a.fill_between(t_arr, _p0_t, _p1_t, where=(_p1_t < _p0_t), alpha=0.15,
                          color=color_azul,   label=r"$p_0 > p_1 \rightarrow$    stable wins")
        if t_gt is not None:
            ax_a.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_a.text(t_gt, 0.98, r"  $t_{gt}$", color="black", fontsize=9,
                      va="top", transform=ax_a.get_xaxis_transform(), clip_on=True)
        ax_a.set_xlabel("Time [s]", fontsize=11)
        ax_a.set_ylabel(r"$p(H(t))$", fontsize=11)
        ax_a.set_title(r"PDF values at each segment's entropy $H(t)$", fontsize=10)
        ax_a.legend(fontsize=8, loc="upper left")
        _shade_intervals_local(ax_a, training_intervals)

        ax_b.plot(t_arr, _ratio, color=color_verde, lw=1.2,
                  label=r"$p_1(H(t))\,/\,p_0(H(t))$  (likelihood ratio per segment)")
        ax_b.axhline(1.0, color="gray", ls=":", lw=0.9, label="ratio = 1  (indifferent)")
        if t_gt is not None:
            ax_b.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_b.text(t_gt, 0.98, r"  $t_{gt}$", color="black", fontsize=9,
                      va="top", transform=ax_b.get_xaxis_transform(), clip_on=True)
        ax_b.set_xlabel("Time [s]", fontsize=11)
        ax_b.set_ylabel(r"$p_1 / p_0$", fontsize=11)
        ax_b.set_title(r"Likelihood ratio per segment  ($> 1$: evidence for chatter)", fontsize=10)
        ax_b.legend(fontsize=8, loc="upper left")
        _shade_intervals_local(ax_b, training_intervals)

        return fig, (ax_a, ax_b)

    def _plot_D8_figure(
        t_arr, H_arr,
        P0_mu, P0_sig, P1_mu, P1_sig,
        t_gt=None, training_intervals=None,
        scale=5.0,
        fig_label=None,
    ):
        """D8 — ln p0(H(t)) and ln p1(H(t)) over time (top) + Lambda_k increments (bottom)."""
        _p0_t  = _norm_dist.pdf(H_arr, P0_mu, P0_sig)
        _p1_t  = _norm_dist.pdf(H_arr, P1_mu, P1_sig)
        _lp0_t = np.log(np.maximum(_p0_t, 1e-300))
        _lp1_t = np.log(np.maximum(_p1_t, 1e-300))
        _Lk_t  = _lp1_t - _lp0_t

        fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale),
                                          constrained_layout=True, num=fig_label)
        fig.suptitle(r"D8 - $\ln p_0(H(t))$ and $\ln p_1(H(t))$ over time"
                     "\n(log-likelihoods and their difference = $\Lambda_k$)", fontsize=12)

        ax_a.plot(t_arr, _lp0_t, color=color_azul,  lw=1.2,
                  label=r"$\ln p_0(H(t))$  (log-prob stable)")
        ax_a.plot(t_arr, _lp1_t, color=color_orange, lw=1.2,
                  label=r"$\ln p_1(H(t))$  (log-prob chatter)")
        ax_a.fill_between(t_arr, _lp0_t, _lp1_t, where=(_lp1_t > _lp0_t), alpha=0.12,
                          color=color_orange, label=r"$\ln p_1 > \ln p_0 \rightarrow$    chatter more likely")
        ax_a.fill_between(t_arr, _lp0_t, _lp1_t, where=(_lp1_t < _lp0_t), alpha=0.12,
                          color=color_azul,   label=r"$\ln p_0 > \ln p_1 \rightarrow$    stable more likely")
        if t_gt is not None:
            ax_a.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_a.text(t_gt, 0.98, r"  $t_{gt}$", color="black", fontsize=9,
                      va="top", transform=ax_a.get_xaxis_transform(), clip_on=True)
        ax_a.set_xlabel("Time [s]", fontsize=11)
        ax_a.set_ylabel(r"$\ln p(H(t))$", fontsize=11)
        ax_a.set_title(r"Log-likelihoods at each segment  (gap = $\Lambda_k$)", fontsize=10)
        ax_a.legend(fontsize=8, loc="lower left")
        _shade_intervals_local(ax_a, training_intervals)

        ax_b.plot(t_arr, _Lk_t, color=color_verde, lw=1.0, alpha=0.8,
                  label=r"$\Lambda_k = \ln p_1(H(t)) - \ln p_0(H(t))$  \u2190 fed into $S_k$")
        ax_b.axhline(0, color="gray", ls=":", lw=0.9)
        ax_b.fill_between(t_arr, _Lk_t, 0, where=(_Lk_t > 0), alpha=0.15, color=color_orange,
                          label=r"$\Lambda_k > 0$: pushes $S_k$ toward chatter")
        ax_b.fill_between(t_arr, _Lk_t, 0, where=(_Lk_t < 0), alpha=0.15, color=color_azul,
                          label=r"$\Lambda_k < 0$: pushes $S_k$ toward stable")
        if t_gt is not None:
            ax_b.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_b.text(t_gt, 0.98, r"  $t_{gt}$", color="black", fontsize=9,
                      va="top", transform=ax_b.get_xaxis_transform(), clip_on=True)
        ax_b.set_xlabel("Time [s]", fontsize=11)
        ax_b.set_ylabel(r"$\Lambda_k$", fontsize=11)
        ax_b.set_title(r"$\Lambda_k$ per segment over time  (increments of $S_k$)", fontsize=10)
        ax_b.legend(fontsize=8, loc="upper left")
        _shade_intervals_local(ax_b, training_intervals)

        return fig, (ax_a, ax_b)

    def _plot_D9_figure(
        t_arr, H_online,
        H_stable_train, H_chatter_train,
        P0_mu, P0_sig, P1_mu, P1_sig,
        alpha_val, training_intervals=None,
        scale=5.0,
        fig_label=None,
    ):
        """D9 — Analytical PDFs with alpha/beta fills (left) + real histogram + fit (right)."""
        H_lo = P0_mu - 4.5 * P0_sig
        H_hi = P1_mu + 4.5 * P1_sig
        H_ax = np.linspace(H_lo, H_hi, 800)
        pdf0 = _norm_dist.pdf(H_ax, P0_mu, P0_sig)
        pdf1 = _norm_dist.pdf(H_ax, P1_mu, P1_sig)
        _H_thr  = P0_mu + _norm_dist.isf(alpha_val) * P0_sig
        _a_real = float(_norm_dist.sf(_H_thr,  P0_mu, P0_sig))
        _b_real = float(_norm_dist.cdf(_H_thr, P1_mu, P1_sig))
        _lam    = _norm_dist.logpdf(H_ax, P1_mu, P1_sig) - _norm_dist.logpdf(H_ax, P0_mu, P0_sig)
        _cross  = float(H_ax[np.argmin(np.abs(_lam))])
        _y_top  = max(pdf0.max(), pdf1.max())

        # Split H_online by training labels (same regions used to fit P0/P1)
        if training_intervals is not None and t_arr is not None and H_online is not None and len(H_online) > 0:
            _ms = np.zeros(len(t_arr), dtype=bool)
            _mc = np.zeros(len(t_arr), dtype=bool)
            for _t0, _t1, _lbl in training_intervals:
                _mm = (np.asarray(t_arr) >= _t0) & (np.asarray(t_arr) < _t1)
                if str(_lbl).lower() == "stable":
                    _ms |= _mm
                else:
                    _mc |= _mm
            _H_s = np.asarray(H_online)[_ms]
            _H_c = np.asarray(H_online)[_mc]
        else:
            _H_s = H_stable_train  if H_stable_train  is not None else np.array([])
            _H_c = H_chatter_train if H_chatter_train is not None else np.array([])

        fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale),
                                          constrained_layout=True, num=fig_label)
        fig.suptitle(
            r"D9 - Both distributions $P_0$ (stable) and $P_1$ (chatter): "
            "theory and measured $H$ values", fontsize=13)

        # Left: analytical PDFs with alpha/beta fills
        ax_a.plot(H_ax, pdf0, color=color_azul,   lw=2.2,
                  label=rf"$p_0(H)\;\sim\mathcal{{N}}(\mu_0={P0_mu:.3f},\;\sigma_0={P0_sig:.3f})$ nat")
        ax_a.plot(H_ax, pdf1, color=color_orange,  lw=2.2,
                  label=rf"$p_1(H)\;\sim\mathcal{{N}}(\mu_1={P1_mu:.3f},\;\sigma_1={P1_sig:.3f})$ nat")
        ax_a.fill_between(H_ax, pdf0, where=(H_ax >= _H_thr), alpha=0.35, color=color_red,
                          label=rf"$\alpha$ (false alarm) $= {_a_real:.5f}$")
        ax_a.fill_between(H_ax, pdf1, where=(H_ax <= _H_thr), alpha=0.25, color=color_verde,
                          label=rf"$\beta$ (miss rate) $= {_b_real:.4f}$")
        ax_a.fill_between(H_ax, np.minimum(pdf0, pdf1), alpha=0.10, color="gray",
                          label="Overlap region")
        for _xv, _lbl, _col, _ha in [
            (P0_mu,  rf"$\mu_0={P0_mu:.2f}$",        color_azul,   "right"),
            (P1_mu,  rf"$\mu_1={P1_mu:.2f}$",        color_orange,  "left"),
            (_H_thr, rf"$H_{{thr}}={_H_thr:.2f}$",   color_red,     "right"),
            (_cross, r"$\Lambda\!=\!0$",              "gray",        "left"),
        ]:
            ax_a.axvline(_xv, color=_col, ls="--", lw=1.0, alpha=0.75)
            ax_a.text(_xv, 0.97, f"  {_lbl}", color=_col, fontsize=8,
                      ha=_ha, va="top", transform=ax_a.get_xaxis_transform(), clip_on=True)
        for _mu, _sig, _col in [(P0_mu, P0_sig, color_azul), (P1_mu, P1_sig, color_orange)]:
            ax_a.annotate("", xy=(_mu + 3*_sig, -0.008*_y_top),
                          xytext=(_mu - 3*_sig, -0.008*_y_top),
                          arrowprops=dict(arrowstyle="<->", color=_col, lw=1.2),
                          annotation_clip=False, clip_on=True)
            ax_a.text(_mu, -0.03*_y_top, r"$\pm3\sigma$",
                      ha="center", va="top", fontsize=7, color=_col, clip_on=False)
        ax_a.set_xlabel(r"Segment entropy $H$  [nat]", fontsize=11)
        ax_a.set_ylabel(r"Probability density  [nat$^{-1}$]", fontsize=11)
        ax_a.set_title(r"Analytical $P_0$ / $P_1$ with error regions $\alpha$, $\beta$", fontsize=10)
        ax_a.set_xlim(H_lo, H_hi)
        ax_a.set_ylim(bottom=-0.06 * _y_top)
        ax_a.legend(fontsize=8, loc="upper right", framealpha=0.93)

        # Right: real histogram + fitted PDFs
        if len(_H_s) > 0:
            ax_b.hist(_H_s, bins=50, density=True, color=color_azul,   alpha=0.45,
                      label=f"Training stable  ($n={len(_H_s)}$ seg.)")
        if len(_H_c) > 0:
            ax_b.hist(_H_c, bins=50, density=True, color=color_orange,  alpha=0.45,
                      label=f"Training chatter ($n={len(_H_c)}$ seg.)")
        ax_b.plot(H_ax, pdf0, color=color_azul,   lw=2.2, ls="-", label=r"Fitted $p_0(H)$")
        ax_b.plot(H_ax, pdf1, color=color_orange,  lw=2.2, ls="-", label=r"Fitted $p_1(H)$")
        ax_b.axvline(_H_thr, color=color_red, ls="--", lw=1.2)
        ax_b.axvline(_cross,  color="gray",   ls=":",  lw=0.9)
        ax_b.text(_H_thr, 0.97, rf"$H_{{thr}}$", color=color_red, fontsize=8,
                  ha="right", va="top", transform=ax_b.get_xaxis_transform(), clip_on=True)
        ax_b.text(_cross,  0.97, r"  $\Lambda\!=\!0$", color="gray", fontsize=8,
                  ha="left",  va="top", transform=ax_b.get_xaxis_transform(), clip_on=True)
        if len(_H_s) > 0 and len(_H_c) > 0:
            _mu0m = float(np.mean(_H_s));  _s0m = float(np.std(_H_s))
            _mu1m = float(np.mean(_H_c));  _s1m = float(np.std(_H_c))
            _txt = (
                "Training segs. vs fitted\n"
                rf"$\mu_0$:  {_mu0m:.3f}  (fit {P0_mu:.3f})" "\n"
                rf"$\sigma_0$: {_s0m:.3f}  (fit {P0_sig:.3f})" "\n"
                rf"$\mu_1$:  {_mu1m:.3f}  (fit {P1_mu:.3f})" "\n"
                rf"$\sigma_1$: {_s1m:.3f}  (fit {P1_sig:.3f})"
            )
            ax_b.text(0.02, 0.97, _txt, transform=ax_b.transAxes, fontsize=7.5,
                      va="top", ha="left",
                      bbox=dict(boxstyle="round,pad=0.4", fc="white", ec="gray", alpha=0.85), clip_on=True)
        ax_b.set_xlabel(r"Segment entropy $H$  [nat]", fontsize=11)
        ax_b.set_ylabel("Density (normalised histogram)", fontsize=11)
        ax_b.set_title(r"Real signal: histogram of $H$ values vs fitted Gaussians", fontsize=10)
        ax_b.set_xlim(H_lo, H_hi)
        ax_b.legend(fontsize=8, loc="upper right", framealpha=0.93)

        return fig, (ax_a, ax_b)

    def _plot_D4_figure(
        t_arr, H_arr, Sk_arr,
        P0_mu, P0_sig,
        P1_mu, P1_sig,
        b_val, a_val,
        t_gt=None, training_intervals=None,
        t_det_sprt=None,
        scale=5.0,
        fig_label=None,
    ):
        """D4 — S_k(t) accumulated + Λ_k log-likelihood increments, shared Y axis."""
        t_arr  = np.asarray(t_arr)
        Sk_arr = np.asarray(Sk_arr)
        H_arr  = np.asarray(H_arr)

        # Λ_k = ln p1(H_k) - ln p0(H_k)  (analytical, same as D8)
        _lp0 = np.log(np.maximum(_norm_dist.pdf(H_arr, P0_mu, P0_sig), 1e-300))
        _lp1 = np.log(np.maximum(_norm_dist.pdf(H_arr, P1_mu, P1_sig), 1e-300))
        lam_arr = _lp1 - _lp0

        # t_d from Λ_k: first time Λ_k crosses b_val
        _cross_idx = np.where(lam_arr >= b_val)[0]
        t_det_lam = float(t_arr[_cross_idx[0]]) if len(_cross_idx) > 0 else None

        fig, ax = plt.subplots(
            figsize=fig_size(scale, ncols=1), constrained_layout=True,
            num="D4 — SPRT statistic and log-likelihood increments",
        )
        ax.set_title(
            r"SPRT statistic $S_k(t)$ and log-likelihood increments $\Lambda_k$"
        )

        # ── Λ_k (increments) — thin, alpha, behind ────────────────────────────
        ax.plot(t_arr, lam_arr, color=color_azul, lw=0.8, marker=".", ms=2,
                alpha=0.55, label=r"$\Lambda_k = \ln\frac{p_1(H_k)}{p_0(H_k)}$")

        # ── S_k (accumulated) ─────────────────────────────────────────────────
        ax.plot(t_arr, Sk_arr, color=color_orange, lw=1.2, marker=".", ms=2,
                alpha=0.90, label=r"$S_k = \sum_{i=1}^{k}\Lambda_i$")

        # ── SPRT decision thresholds ──────────────────────────────────────────
        ax.axhline(b_val, color=color_red,   ls="--", lw=1.5,
                   label=rf"$b = {b_val:.2f}$  (chatter, $\alpha$)")
        ax.axhline(a_val, color=color_verde, ls="--", lw=1.2,
                   label=rf"$a = {a_val:.2f}$  (stable, $\beta$)")
        ax.axhline(0,     color="gray",      ls=":",  lw=0.8)
        ax.text(0.99, b_val, rf"$b={b_val:.2f}$",
                transform=ax.get_yaxis_transform(),
                color=color_red, ha='right', va='bottom', fontsize=16, clip_on=True)
        ax.text(0.99, a_val, rf"$a={a_val:.2f}$",
                transform=ax.get_yaxis_transform(),
                color=color_verde, ha='right', va='top', fontsize=16, clip_on=True)

        # ── Vertical event lines ──────────────────────────────────────────────
        if t_gt is not None:
            ax.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax.text(t_gt, 0.97, f"  $t_{{gt}}={t_gt:.3f}$ s",
                    rotation=90, va="top", ha="right",
                    color="black", transform=ax.get_xaxis_transform(), fontsize=16, clip_on=True)
        if t_det_lam is not None:
            ax.axvline(t_det_lam, color=color_azul, ls="-.", lw=1.3)
            ax.text(t_det_lam, 0.87, rf"  $t_{{d,\Lambda}}={t_det_lam:.3f}$ s",
                    rotation=90, va="top", ha="right",
                    color=color_azul, transform=ax.get_xaxis_transform(), fontsize=16, clip_on=True)
        if t_det_sprt is not None:
            ax.axvline(t_det_sprt, color=color_red, ls="-.", lw=1.3)
            ax.text(t_det_sprt, 0.75, rf"  $t_{{d,S_k}}={t_det_sprt:.3f}$ s",
                    rotation=90, va="top", ha="right",
                    color=color_red, transform=ax.get_xaxis_transform(), fontsize=16, clip_on=True)

        apply_sci_yaxis(ax)
        ax.set_xlabel("Time [s]")
        ax.set_ylabel(r"Log-likelihood ratio")
        ax.legend(loc="best", fontsize=12)
        return fig, (ax, ax)

    def _plot_H_Sk_joint(
        t_arr, H_arr, Sk_arr,
        lim_sup, lim_inf,
        t_gt=None, training_intervals=None,
        t_d_first=None, scale=5.0,
        fig_label=None,
    ):
        """H(t) + Sk(t) joint diagnostic: H(t) on top subplot, Sk(t) on bottom (shared x-axis).

        ``t_d_first`` is the single authoritative first-detection marker — only
        that plus ``t_gt`` are ever drawn as vertical lines here, never one per
        detection.
        """
        fig, (ax_h, ax_s) = plt.subplots(1, 2, figsize=figsize_from_scale(FIGSIZE_WIDE, scale),
                                          constrained_layout=True, num=fig_label)
        fig.suptitle(r"Entropy $H(t)$ and SPRT statistic $S_k(t)$  - joint diagnostic")

        # Top: H(t), single colour — just the evolution, no training-label split.
        ax_h.plot(t_arr, H_arr, color=color_azul, marker='.', lw=0.8)
        if t_gt is not None:
            ax_h.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_h.text(t_gt, 0.97, f"  $t_{{gt}}={t_gt:.3f}$ s", color="black", fontsize=16,
                      va="top", ha="right", rotation=90, transform=ax_h.get_xaxis_transform(), clip_on=True)

        if t_d_first is not None:
            ax_h.axvline(t_d_first, color=color_red, ls="-.", lw=1.5)
            ax_h.text(t_d_first, 0.97, f"  $t_d={t_d_first:.3f}$ s",
                      rotation=90, va="top", ha="right", fontsize=16,
                      color=color_red, transform=ax_h.get_xaxis_transform(), clip_on=True)
            
        ax_h.set_xlabel("Time [s]", fontsize=11)
        ax_h.set_ylabel(r"Entropy $H(t)$ [nat]", fontsize=11)
        ax_h.set_title(r"Online entropy $H(t)$", fontsize=10)

        # Bottom: Sk(t)
        ax_s.plot(np.asarray(t_arr), np.asarray(Sk_arr), color=color_purple,
                  marker='.', lw=0.8, label=r"$S_k$")
        ax_s.axhline(lim_sup, color=color_red,  ls="--", lw=1.5,
                     label=rf"$b = {lim_sup:.2f}$ (chatter, $\alpha$)")
        ax_s.axhline(lim_inf, color=color_azul, ls="--", lw=1.5,
                     label=rf"$a = {lim_inf:.2f}$ (stable, $\beta$)")
        ax_s.axhline(0, color="gray", ls=":", lw=0.9)
        apply_sci_yaxis(ax_s)
        if t_gt is not None:
            ax_s.axvline(t_gt, color="black", ls="--", lw=1.2)
            ax_s.text(t_gt, 0.97, f"  $t_{{gt}}={t_gt:.3f}$ s", color="black", fontsize=16,
                      va="top", ha="right", rotation=90, transform=ax_s.get_xaxis_transform(), clip_on=True)
        
        if t_d_first is not None:
            ax_s.axvline(t_d_first, color=color_red, ls="-.", lw=1.5)
            ax_s.text(t_d_first, 0.97, f"  $t_d={t_d_first:.3f}$ s",
                      rotation=90, va="top", ha="right", fontsize=16,
                      color=color_red, transform=ax_s.get_xaxis_transform(), clip_on=True)
        _shade_intervals_local(ax_s, training_intervals)
        ax_s.set_xlabel("Time [s]", fontsize=11)
        ax_s.set_ylabel(r"$S_k$", fontsize=11)
        ax_s.set_title(r"SPRT statistic $S_k$  (accumulates $\Lambda_k$ increments)", fontsize=10)
        ax_s.legend(fontsize=8, loc="upper left")
        return fig, (ax_h, ax_s)

    def _plot_signal_full_online(
        t_sig, v_sig,
        training_intervals=None,
        t_gt=None,
        opr_t_stable=None, opr_v_stable=None,
        opr_t_chatter=None, opr_v_chatter=None,
        title="O4 — Signal + OPR Sampling (Online — full signal)",
        zoom_x=None, zoom_y=None,
        scale=1.0,
        fig_label=None,
    ):
        """Single panel: full analysis signal with training-interval shading and OPR marks."""
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        if t_sig is not None and v_sig is not None and len(t_sig) > 0:
            ax.plot(t_sig, v_sig, color="gray", lw=0.7, alpha=0.85, label="Signal")
        if opr_t_stable is not None and opr_v_stable is not None and len(opr_t_stable) > 0:
            ax.scatter(opr_t_stable, opr_v_stable, color=color_azul, s=7, zorder=5,
                       label="OPR — stable training")
        if opr_t_chatter is not None and opr_v_chatter is not None and len(opr_t_chatter) > 0:
            ax.scatter(opr_t_chatter, opr_v_chatter, color=color_orange, s=7, zorder=5,
                       label="OPR — chatter training")
        if t_gt is not None:
            ax.axvline(t_gt, color="black", ls="--", lw=1.2,
                       label=f"$t_{{gt}} = {t_gt:.3f}$ s")
            ax.text(t_gt, 0.97, f"  $t_{{gt}}={t_gt:.3f}$ s",
                    rotation=90, va="top", ha="right",
                    color="black", transform=ax.get_xaxis_transform(), clip_on=True)
        _shade_intervals_local(ax, training_intervals)
        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(r"$v(t)$")
        ax.legend()
        return fig, ax

    def _plot_signal_first_detection(
        t_sig, v_sig,
        vlines=None,
        title="Analyzed Signal — First Detection",
        zoom_x=None, zoom_y=None,
        scale=1.0,
        fig_label=None,
    ):
        """Single panel: the raw analyzed signal with just the first-detection vline."""
        fig, ax = plt.subplots(figsize=fig_size(scale=scale, ncols=1),
                                constrained_layout=True, num=fig_label)
        if t_sig is not None and v_sig is not None and len(t_sig) > 0:
            ax.plot(t_sig, v_sig, color="gray", lw=0.7, alpha=0.85)
        _draw_vlines(ax, vlines)
        if zoom_x is not None:
            ax.set_xlim(zoom_x)
        if zoom_y is not None:
            ax.set_ylim(zoom_y)
        ax.set_title(title)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(r"$v(t)$")
        return fig, ax

    # ──────────────────────────────────────────────────────────────────

    configurar_estilo_global()

    meta = result.meta or {}

    # ── Signal and OPR data ───────────────────────────────────────────
    t_stable                = meta.get("t_stable", None)
    signal_analysis_stable  = meta.get("signal_analysis_stable", None)
    t_chatter               = meta.get("t_chatter", None)
    signal_analysis_chatter = meta.get("signal_analysis_chatter", None)
    t_opr_free              = meta.get("t_opr_free", None)
    opr_free                = meta.get("opr_free", None)
    t_opr_chat              = meta.get("t_opr_chat", None)
    opr_chat                = meta.get("opr_chat", None)

    # ── Offline training entropy ──────────────────────────────────────
    detector   = meta.get("detector", None)
    H_free     = detector.H_free     if detector is not None else None
    H_chat     = detector.H_chat     if detector is not None else None
    t_mid_free = detector.t_mid_free if detector is not None else None
    t_mid_chat = detector.t_mid_chat if detector is not None else None

    # ── Model parameters ─────────────────────────────────────────────
    P0_mu    = meta.get("P0_mu",    0.0)
    P0_sigma = meta.get("P0_sigma", 1.0)
    P1_mu    = meta.get("P1_mu",    0.0)
    P1_sigma = meta.get("P1_sigma", 1.0)

    # ── Training data provenance (internal cut vs reference_signal[_chatter]) ──
    # Not shown as title text (the curves themselves, sourced from meta/detector
    # rather than recomputed here, are the verification — see
    # examples/test_reference_signal.py for the assert-based check). Still used
    # below to decide whether t_gt/t_d markers are meaningful on a given axis.
    training_source = meta.get("training_source", "internal")
    chatter_source  = meta.get("chatter_source",  "internal")
    _both_internal = training_source == "internal" and chatter_source == "internal"

    # ── Online indicator history ──────────────────────────────────────
    t_i          = result.t
    I            = result.I_t
    H_seq_online = np.asarray(meta.get("H_seq_online", [])) if meta.get("H_seq_online") is not None else np.array([])
    lim_sup      = meta.get("sprt_result").b
    lim_inf      = meta.get("sprt_result").a

    # ── Auto vertical lines ───────────────────────────────────────────
    # Rule: the only vertical lines allowed on a detection-over-time panel are
    # (a) t_gt/t_theorical and (b) the single first detection — never one line
    # per detection. Deliberately the RAW first detection (result.t_d[0]), not
    # result.t_d_no_FAR[0] — the latter is by construction always > t_gt, which
    # would hide early/false triggers instead of showing them.
    _t_d = np.asarray(result.t_d) if result.t_d is not None and len(result.t_d) > 0 else np.array([])
    _t_first_det = float(_t_d[0]) if _t_d.size > 0 else None
    _avl = []
    if t_gt is not None:
        _avl.append((t_gt,         f"$t_{{gt}}={t_gt:.3f}$ s", "black"))
    if _t_first_det is not None:
        _avl.append((_t_first_det, f"$t_d={_t_first_det:.3f}$ s", color_orange))
    auto_vlines = _avl if _avl else None

    _ti_meta = meta.get("training_intervals", None)

    kw = dict(zoom_x=zoom_x, zoom_y=zoom_y, vlines=vlines, hlines=hlines, scale=scale)
    kw_auto = dict(zoom_x=zoom_x, zoom_y=zoom_y, vlines=auto_vlines, hlines=hlines, scale=scale)

    # ══════════════════════════════════════════════════════════════════
    # ONLINE FIGURES (O3–O4)
    # ══════════════════════════════════════════════════════════════════

    # O3 — Online entropy: full signal, single colour (just the evolution, no
    # hardcoded stable/chatter split) — t_gt still marked via the explicit vline.
    fig_O3, ax_O3 = _plot_H_time_all(
        t_i, H_seq_online, t_split=None,
        training_intervals=None,
        title="Online Entropy — Full Evolution",
        fig_label="O3 — Online Entropy: Full Evolution",
        zoom_x=zoom_x, zoom_y=zoom_y,
        vlines=[(t_gt, f"$t_{{gt}}={t_gt:.3f}$ s")] if t_gt is not None else None,
        hlines=hlines, scale=scale,
    )

    # O4 — Full online signal + training OPR marks (single panel)
    fig_O4, ax_O4 = _plot_signal_full_online(
        signal.t_analysis if signal is not None else None,
        signal.signal_analysis if signal is not None else None,
        training_intervals=_ti_meta,
        t_gt=t_gt,
        opr_t_stable=t_opr_free, opr_v_stable=opr_free,
        opr_t_chatter=t_opr_chat, opr_v_chatter=opr_chat,
        title="O4 — Signal + OPR Sampling (Online — full signal)",
        zoom_x=zoom_x, zoom_y=zoom_y, scale=scale,
        fig_label="O4 — Signal + OPR Sampling (Online)",
    )

    # O5 — Analyzed signal, single color, only the first-detection vline
    # (same $t_d$ style as everywhere else -- no t_gt, no OPR, no shading).
    _vlines_first_det = (
        [(_t_first_det, f"$t_d={_t_first_det:.3f}$ s", color_orange)]
        if _t_first_det is not None else None
    )
    fig_O5, ax_O5 = _plot_signal_first_detection(
        signal.t_analysis if signal is not None else None,
        signal.signal_analysis if signal is not None else None,
        vlines=_vlines_first_det,
        title="O5 — Analyzed Signal: First Detection",
        zoom_x=zoom_x, zoom_y=zoom_y, scale=scale,
        fig_label="O5 — Analyzed Signal: First Detection",
    )

    # ══════════════════════════════════════════════════════════════════
    # OFFLINE / TRAINING FIGURES (F0–F7)
    # ══════════════════════════════════════════════════════════════════

    # ── Piece-gap views for F0/F1/F2/F3/F6 only: when training data comes from
    # several physically-disjoint pieces (reference_signal pieces or multiple
    # training_intervals of the same label), a plain line plot over the flat
    # concatenated arrays would draw a straight line across the seam between
    # two unrelated pieces. Splice a NaN at each piece boundary so the line
    # breaks there instead -- display only, H_free/H_chat/t_mid_free/t_mid_chat
    # themselves (used for the F4/F5/F7 fit histograms) are untouched.
    _t_stable_g,  _sig_stable_g  = _nan_split(t_stable,  signal_analysis_stable,  meta.get("stable_piece_sizes"))
    _t_chatter_g, _sig_chatter_g = _nan_split(t_chatter, signal_analysis_chatter, meta.get("chatter_piece_sizes"))
    _t_opr_free_g, _opr_free_g   = _nan_split(t_opr_free, opr_free, meta.get("opr_free_piece_sizes"))
    _t_opr_chat_g, _opr_chat_g   = _nan_split(t_opr_chat, opr_chat, meta.get("opr_chat_piece_sizes"))
    _t_mid_free_g, _H_free_g     = _nan_split(t_mid_free, H_free, meta.get("n_windows_per_piece_free"))
    _t_mid_chat_g, _H_chat_g     = _nan_split(t_mid_chat, H_chat, meta.get("n_windows_per_piece_chat"))

    # F0 — Verification: raw signal that actually fed the P0/P1 Gaussian fit
    # (internal cut or reference_signal[_chatter] — see meta["training_source"]).
    # One grid per side (stable/chatter never mixed in the same grid) so each
    # contributing case (DOE reference_signal piece) is individually legible.
    fig_F0a, axes_F0a = _plot_pieces_grid(
        t_stable, signal_analysis_stable, meta.get("stable_piece_sizes"),
        None, None, None,
        color_azul, "Stable", "F0a — Training Signal Used for P0 Fit (Stable, per case)",
        scale=grid_scale,
        fig_label="F0a — Training Signal Verification (Stable, per case)",
    )
    fig_F0b, axes_F0b = _plot_pieces_grid(
        t_chatter, signal_analysis_chatter, meta.get("chatter_piece_sizes"),
        None, None, None,
        color_orange, "Chatter", "F0b — Training Signal Used for P1 Fit (Chatter, per case)",
        scale=grid_scale,
        fig_label="F0b — Training Signal Verification (Chatter, per case)",
    )

    # F1 — Training entropy: stable, one grid cell per case (same rationale as F0a)
    fig_F1, axes_F1 = _plot_pieces_grid(
        t_mid_free, H_free, meta.get("n_windows_per_piece_free"),
        None, None, None,
        color_azul, "Stable", "F1 — Training Entropy: Stable Segments (per case)",
        zoom_x=kw["zoom_x"], zoom_y=kw["zoom_y"], vlines=kw["vlines"], hlines=kw["hlines"],
        scale=grid_scale,
        fig_label="F1 — Training Entropy: Stable Segments",
        ylabel="Entropy $H$",
    )

    # F1b — one figure per distinct stable label (only if ≥2 distinct stable labels)
    if _ti_meta is not None and H_free is not None and t_mid_free is not None:
        _stable_groups_t: dict = {}
        for _t0, _t1, _lbl in _ti_meta:
            _lbl_lo = str(_lbl).lower().strip()
            if _lbl_lo.startswith("stable"):
                _stable_groups_t.setdefault(_lbl_lo, []).append((_t0, _t1))
        if len(_stable_groups_t) >= 2:
            _H_free_arr = np.asarray(H_free)
            _t_free_arr = np.asarray(t_mid_free)
            for _gi, (_lbl_name, _ranges) in enumerate(_stable_groups_t.items()):
                _plot_H_time_one_segment(
                    _t_free_arr, _H_free_arr,
                    seg_ranges=_ranges,
                    seg_label=_lbl_name,
                    color_all=color_azul,
                    color_seg=color_azul,
                    title=(
                        r"Training Entropy — Stable "
                        rf"| {_lbl_name}"
                    ),
                    fig_label=f"F1b.{_gi} — {_lbl_name}",
                    **kw,
                )

    # F2 — Training entropy: chatter, one grid cell per case (same rationale as F0a)
    fig_F2, axes_F2 = _plot_pieces_grid(
        t_mid_chat, H_chat, meta.get("n_windows_per_piece_chat"),
        None, None, None,
        color_orange, "Chatter", "F2 — Training Entropy: Chatter Segments (per case)",
        zoom_x=kw["zoom_x"], zoom_y=kw["zoom_y"], vlines=kw["vlines"], hlines=kw["hlines"],
        scale=grid_scale,
        fig_label="F2 — Training Entropy: Chatter Segments",
        ylabel="Entropy $H$",
    )

    # F2b — one figure per distinct chatter label (only if ≥2 distinct chatter labels)
    if _ti_meta is not None and H_chat is not None and t_mid_chat is not None:
        _chatter_groups_t: dict = {}
        for _t0, _t1, _lbl in _ti_meta:
            _lbl_lo = str(_lbl).lower().strip()
            if _lbl_lo.startswith("chatter"):
                _chatter_groups_t.setdefault(_lbl_lo, []).append((_t0, _t1))
        if len(_chatter_groups_t) >= 2:
            _H_chat_arr = np.asarray(H_chat)
            _t_chat_arr = np.asarray(t_mid_chat)
            for _gi, (_lbl_name, _ranges) in enumerate(_chatter_groups_t.items()):
                _plot_H_time_one_segment(
                    _t_chat_arr, _H_chat_arr,
                    seg_ranges=_ranges,
                    seg_label=_lbl_name,
                    color_all=color_orange,
                    color_seg=color_orange,
                    title=(
                        r"Training Entropy — Chatter "
                        rf"| {_lbl_name}"
                    ),
                    fig_label=f"F2b.{_gi} — {_lbl_name}",
                    **kw,
                )

    # F3 — Training entropy: F1 (stable) + F2 (chatter) combined on one axis.
    # Previously masked by training_intervals' [t0, t1] ranges, which assumed
    # t_mid_free/t_mid_chat live on the analyzed signal's timeline — false once
    # reference_signal[_chatter] puts them on an unrelated external timeline
    # (silently dropping or truncating a curve). Just plot both full curves.
    fig_F3, ax_F3 = plt.subplots(
        figsize=fig_size(scale=scale, ncols=1), constrained_layout=True,
        num="F3 — Training Entropy: All Labels",
    )
    if _t_mid_free_g is not None and _H_free_g is not None:
        ax_F3.plot(_t_mid_free_g, _H_free_g, color=color_azul,   lw=1.2,
                   marker='o', markersize=2, label="Stable")
    if _t_mid_chat_g is not None and _H_chat_g is not None:
        ax_F3.plot(_t_mid_chat_g, _H_chat_g, color=color_orange, lw=1.2,
                   marker='o', markersize=2, label="Chatter")
    # t_gt/t_d markers reference the online analyzed-signal timeline: only draw
    # them here when BOTH curves actually live on that same timeline (internal).
    _draw_vlines(ax_F3, auto_vlines if _both_internal else None)
    ax_F3.set_title("F3 — Training Entropy: All Intervals")
    ax_F3.set_xlabel("Time (s)")
    ax_F3.set_ylabel("Entropy $H$")
    ax_F3.legend()


    # F4 — PDF: stable entropy histogram + P0 Gaussian + sigma lines
    fig_F4, ax_F4 = _plot_PDF_hist(
        H_free, mu=P0_mu, sigma=P0_sigma,
        color_hist=color_azul, color_pdf=color_verde,
        title=r"Training PDF — Stable Entropy ($P_0$)",
        fig_label="F4 — Training PDF: Stable (P0)",
        **kw,
    )

    # F4b — one figure per distinct stable label (only if ≥2 distinct stable labels)
    if _ti_meta is not None and H_free is not None and t_mid_free is not None:
        # group intervals by their exact label (e.g. "stable_1", "stable_2")
        _stable_groups: dict = {}
        for _t0, _t1, _lbl in _ti_meta:
            _lbl_lo = str(_lbl).lower().strip()
            if _lbl_lo.startswith("stable"):
                _stable_groups.setdefault(_lbl_lo, []).append((_t0, _t1))
        if len(_stable_groups) >= 2:
            _H_free_arr = np.asarray(H_free)
            _t_free_arr = np.asarray(t_mid_free)
            for _gi, (_lbl_name, _ranges) in enumerate(_stable_groups.items()):
                _flabel = f"F4b.{_gi} — {_lbl_name}"
                _plot_PDF_hist_one_segment(
                    _H_free_arr, _t_free_arr,
                    seg_ranges=_ranges,
                    mu=P0_mu, sigma=P0_sigma,
                    seg_label=_lbl_name,
                    color_all=color_azul, color_seg=color_azul,
                    color_pdf=color_verde,
                    title=(
                        r"Training PDF — Stable $P_0$ "
                        rf"| {_lbl_name}"
                    ),
                    fig_label=_flabel,
                    **kw,
                )

    # F5 — PDF: chatter entropy histogram + P1 Gaussian + sigma lines
    fig_F5, ax_F5 = _plot_PDF_hist(
        H_chat, mu=P1_mu, sigma=P1_sigma,
        color_hist=color_orange, color_pdf=color_red,
        title=r"Training PDF — Chatter Entropy ($P_1$)",
        fig_label="F5 — Training PDF: Chatter (P1)",
        **kw,
    )

    # F5b — one figure per distinct chatter label (only if ≥2 distinct chatter labels)
    if _ti_meta is not None and H_chat is not None and t_mid_chat is not None:
        # group intervals by their exact label (e.g. "chatter_1", "chatter_2")
        _chatter_groups: dict = {}
        for _t0, _t1, _lbl in _ti_meta:
            _lbl_lo = str(_lbl).lower().strip()
            if _lbl_lo.startswith("chatter"):
                _chatter_groups.setdefault(_lbl_lo, []).append((_t0, _t1))
        if len(_chatter_groups) >= 2:
            _H_chat_arr = np.asarray(H_chat)
            _t_chat_arr = np.asarray(t_mid_chat)
            for _gi, (_lbl_name, _ranges) in enumerate(_chatter_groups.items()):
                _flabel = f"F5b.{_gi} — {_lbl_name}"
                _plot_PDF_hist_one_segment(
                    _H_chat_arr, _t_chat_arr,
                    seg_ranges=_ranges,
                    mu=P1_mu, sigma=P1_sigma,
                    seg_label=_lbl_name,
                    color_all=color_orange, color_seg=color_orange,
                    color_pdf=color_red,
                    title=(
                        r"Training PDF — Chatter $P_1$ "
                        rf"| {_lbl_name}"
                    ),
                    fig_label=_flabel,
                    **kw,
                )

    # F6 — Training signal + OPR (stable and chatter, one grid per side)
    # t_gt/t_d markers (drawn on the chatter grid only, matching the old
    # dual-figure's bottom-panel-only placement) reference the online
    # analyzed-signal timeline: suppress them when chatter is external.
    _kw_auto_f6 = dict(kw_auto)
    if chatter_source != "internal":
        _kw_auto_f6["vlines"] = None
    _kw_auto_f6["scale"] = grid_scale
    fig_F6a, axes_F6a = _plot_pieces_grid(
        t_stable, signal_analysis_stable, meta.get("stable_piece_sizes"),
        t_opr_free, opr_free, meta.get("opr_free_piece_sizes"),
        color_azul, "Stable", "F6a — Signal + OPR Sampling (Stable, per case)",
        fig_label="F6a — Signal + OPR Sampling (Stable, per case)",
        zoom_x=kw_auto["zoom_x"], zoom_y=kw_auto["zoom_y"], hlines=kw_auto["hlines"],
        scale=grid_scale,
    )
    fig_F6b, axes_F6b = _plot_pieces_grid(
        t_chatter, signal_analysis_chatter, meta.get("chatter_piece_sizes"),
        t_opr_chat, opr_chat, meta.get("opr_chat_piece_sizes"),
        color_orange, "Chatter", "F6b — Signal + OPR Sampling (Chatter, per case)",
        fig_label="F6b — Signal + OPR Sampling (Chatter, per case)",
        **_kw_auto_f6,
    )

    # F7 — Combined PDF: stable P0 + chatter P1 overlaid in one figure
    fig_F7, ax_F7 = plt.subplots(
        figsize=fig_size(scale=scale, ncols=1), constrained_layout=True,
        num="F7 — Training PDF: Stable vs Chatter",
    )
    if H_free is not None and len(H_free) > 0:
        ax_F7.hist(H_free, density=True, alpha=0.40, color=color_azul,
                   bins=50, label=rf"Stable")
        _x0 = np.linspace(P0_mu - 4.5 * P0_sigma, P0_mu + 4.5 * P0_sigma, 1000)
        ax_F7.plot(_x0,
                   np.exp(-0.5 * ((_x0 - P0_mu) / P0_sigma) ** 2)
                   / (P0_sigma * np.sqrt(2 * np.pi)),
                   color=color_verde, lw=1.8,
                   label=rf"$P_0$: $\mu$={P0_mu:.4f}, $\sigma$={P0_sigma:.4f}")
    if H_chat is not None and len(H_chat) > 0:
        ax_F7.hist(H_chat, density=True, alpha=0.40, color=color_orange,
                   bins=50, label=rf"Chatter")
        _x1 = np.linspace(P1_mu - 4.5 * P1_sigma, P1_mu + 4.5 * P1_sigma, 1000)
        ax_F7.plot(_x1,
                   np.exp(-0.5 * ((_x1 - P1_mu) / P1_sigma) ** 2)
                   / (P1_sigma * np.sqrt(2 * np.pi)),
                   color=color_red, lw=1.8,
                   label=rf"$P_1$: $\mu$={P1_mu:.4f}, $\sigma$={P1_sigma:.4f}")
    ax_F7.set_title(r"F7 — Training PDF: Stable $P_0$ vs Chatter $P_1$")
    ax_F7.set_xlabel("Entropy $H$")
    ax_F7.set_ylabel("Probability Density")
    ax_F7.legend()

    # ══════════════════════════════════════════════════════════════════
    # SPRT FIGURE (S1)
    # ══════════════════════════════════════════════════════════════════

    fig_S1, ax_S1 = _plot_S_n(
        t_i=t_i,
        I=I,
        lim_sup=lim_sup,
        lim_inf=lim_inf,
        scale=scale,
        title=r"S1 — MaxEnt-SPRT Detection Statistic $S_k(t)$",
        zoom_x=zoom_x,
        zoom_y=zoom_y,
        vlines=auto_vlines,
        hlines=hlines,
        fig_label="S1 — MaxEnt-SPRT Detection Statistic Sk",
    )

    # ── alpha / beta from meta ────────────────────────────────────────
    alpha_val = float(meta.get("alpha", 0.00135))
    beta_val  = float(meta.get("beta",  0.00135))

    # ══════════════════════════════════════════════════════════════════
    # THEORY FIGURES (D3, D6, D7, D8, D9, H+Sk joint)
    # ══════════════════════════════════════════════════════════════════

    # D3 — P0/P1 separate panels with alpha and beta error fills
    fig_D3, axes_D3 = _plot_D3_figure(
        P0_mu=P0_mu, P0_sig=P0_sigma,
        P1_mu=P1_mu, P1_sig=P1_sigma,
        alpha_val=alpha_val, beta_val=beta_val,
        a_val=lim_inf, b_val=lim_sup,
        scale=scale,
        fig_label="D3 — Error Regions alpha, beta and SPRT Boundaries",
    )

    # D6 — Log-likelihoods and Lambda(H) as static functions of H
    fig_D6, axes_D6 = _plot_D6_figure(
        P0_mu=P0_mu, P0_sig=P0_sigma,
        P1_mu=P1_mu, P1_sig=P1_sigma,
        alpha_val=alpha_val, a_val=lim_inf, b_val=lim_sup,
        scale=scale,
        fig_label="D6 — Log-Likelihoods and Lambda(H) Static",
    )

    # D7, D8, D9 and H+Sk require the full online H sequence
    if H_seq_online.size > 0 and t_i is not None and len(t_i) > 0:
        _H_arr = H_seq_online
        _t_arr = np.asarray(t_i)

        # D4 — S_k(t) + Lambda_k in one figure
        fig_D4, (ax_D4a, ax_D4b) = _plot_D4_figure(
            t_arr=_t_arr, H_arr=_H_arr, Sk_arr=np.asarray(I),
            P0_mu=P0_mu, P0_sig=P0_sigma,
            P1_mu=P1_mu, P1_sig=P1_sigma,
            b_val=lim_sup, a_val=lim_inf,
            t_gt=t_gt, training_intervals=_ti_meta,
            t_det_sprt=_t_first_det,
            scale=scale,
            fig_label="D4 — Classic mu±3sigma vs MaxEnt-SPRT",
        )

        # D7 — p0(H(t)), p1(H(t)) over time + likelihood ratio
        fig_D7, axes_D7 = _plot_D7_figure(
            t_arr=_t_arr, H_arr=_H_arr,
            P0_mu=P0_mu, P0_sig=P0_sigma,
            P1_mu=P1_mu, P1_sig=P1_sigma,
            t_gt=t_gt, training_intervals=_ti_meta,
            scale=scale,
            fig_label="D7 — Likelihoods over Time p0/p1(H(t))",
        )

        # D8 — ln p0(H(t)), ln p1(H(t)) + Lambda_k increments over time
        fig_D8, axes_D8 = _plot_D8_figure(
            t_arr=_t_arr, H_arr=_H_arr,
            P0_mu=P0_mu, P0_sig=P0_sigma,
            P1_mu=P1_mu, P1_sig=P1_sigma,
            t_gt=t_gt, training_intervals=_ti_meta,
            scale=scale,
            fig_label="D8 — Log-Likelihoods + Lambda_k over Time",
        )

        # D9 — Analytical PDFs + real histogram validation
        fig_D9, axes_D9 = _plot_D9_figure(
            t_arr=_t_arr, H_online=_H_arr,
            H_stable_train=H_free, H_chatter_train=H_chat,
            P0_mu=P0_mu, P0_sig=P0_sigma,
            P1_mu=P1_mu, P1_sig=P1_sigma,
            alpha_val=alpha_val,
            training_intervals=_ti_meta,
            scale=scale,
            fig_label="D9 — PDF Validation: Theory vs Measured",
        )

        # D_JOINT — H(t) + Sk(t) joint diagnostic
        fig_D_JOINT, axes_D_JOINT = _plot_H_Sk_joint(
            t_arr=_t_arr, H_arr=_H_arr, Sk_arr=np.asarray(I),
            lim_sup=lim_sup, lim_inf=lim_inf,
            t_gt=t_gt, training_intervals=_ti_meta,
            t_d_first=_t_first_det, scale=scale,
            fig_label="D_JOINT — H(t) + Sk(t) Joint Diagnostic",
        )

    plt.show()


